In [11]:
import numpy as np
a= np.arange(1,10).reshape(3,3)
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [17]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
np.diag(a,k=1)

array([ 2,  8, 14, 20])

In [31]:
a=np.array([10,12,15,25,28,30,35,42,50])*1290
a


array([12900, 15480, 19350, 32250, 36120, 38700, 45150, 54180, 64500])

In [34]:
#broadcasting 분배해서 더해짐 
a= np.array([10,12,15])
b= np.array([[10],[20]])
a+b

array([[20, 22, 25],
       [30, 32, 35]])

In [55]:
c=np.arange(5)
c=np.vstack([c,c+4,c+14,c+24,c+34])
print(c)
print(c[1::2,:4:2])
print(c[c>20])
print(c[c%3==0])

[[ 0  1  2  3  4]
 [ 4  5  6  7  8]
 [14 15 16 17 18]
 [24 25 26 27 28]
 [34 35 36 37 38]]
[[ 4  6]
 [24 26]]
[24 25 26 27 28 34 35 36 37 38]
[ 0  3  6 15 18 24 27 36]


In [42]:
a = np.array([0,1,2,3,4])
b = np.array([[0], [4], [14], [24], [34]])
a + b 

array([[ 0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38]])

In [57]:
g=np.arange(6).reshape(3,2)
np.tile(g,(2,3))

array([[0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3],
       [4, 5, 4, 5, 4, 5],
       [0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3],
       [4, 5, 4, 5, 4, 5]])

In [78]:
a = np.array([[2,5,4], [3,1,9], [6,8,7]]) 
print(a)
print(np.sort(a,axis=-1).T)
print(np.sort(a.T,axis=0))

[[2 5 4]
 [3 1 9]
 [6 8 7]]
[[2 1 6]
 [4 3 7]
 [5 9 8]]
[[2 1 6]
 [4 3 7]
 [5 9 8]]


In [89]:
c=np.arange(1,5)
c=np.vstack([c,c+7,c+14,c+21])
print(c)
d=np.arange(1,29).reshape(4,-1)[:4,:4]
print(d)
print(c[1::2,1::2])

[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]
 [22 23 24 25]]
[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]
 [22 23 24 25]]
[[ 9 11]
 [23 25]]


In [91]:
#대각행렬 구하는 3가지 방법
print(a.T)
print(a.transpose())
print(np.transpose(a))

[[2 3 6]
 [5 1 8]
 [4 9 7]]
[[2 3 6]
 [5 1 8]
 [4 9 7]]
[[2 3 6]
 [5 1 8]
 [4 9 7]]


In [112]:
a=np.ones((5,5))
a = np.ones([5,5])
print(a)
a[1:4, 1:4] = a[1:4, 1:4]+1
print(a)
a[2,2] = a[2,2]+1
print(a) 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 3. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1.]]


In [123]:
#fancy indexing 
a=np.arange(25).reshape(5,5)
print(a)
a[[0,1,2,3],[1,2,3,4]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 1,  7, 13, 19])

In [ ]:
#broadcasting 

In [127]:
a= np.arange(1,13).reshape(3,4)
print(a)
np.where(a%3==0) #3,6,9,12의 인덱스로 나옴 !! (0,2) (1,1) (2,0) (2,3) <- fancy indexing으로 나옴

a[np.where(a%3==0)] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 3,  6,  9, 12])

In [135]:
a=np.arange(-15,15).reshape(5,6)**2
print(a)
print(np.max(a, axis=1)) #행별 최댓값
#열별 평균
print(np.mean(a, axis=0))

[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]
[225  81   9  64 196]
[81. 76. 73. 72. 73. 76.]


In [143]:
import random 
li = ( "강한샘", '곽유석', '현재은', '김경민', '권상지', '김기범', '김연준', '김인섭', '나윤찬', '남기훈', 
      '도영현','장기영', '류소현', '문범식', '손수한', '옥윤호', '위지원', '윤민영', '장휘재', '조은정', '주기재', '황수림', 'miji') 
a= int(input("숫자 입력:"))
b=random.sample(li,a)
for i,j in enumerate(b):
    print(f"{i+1}번 문제는 {j}입니다")

숫자 입력: 4


1번 문제는 김연준입니다
2번 문제는 옥윤호입니다
3번 문제는 류소현입니다
4번 문제는 위지원입니다


In [144]:
num = int(input("발표자는 몇명입니까?"))
names = random.sample(li, k = num)
for i, name in enumerate(names):
    print(f'{i+1}번째는 {name}입니다.') 

발표자는 몇명입니까? 1


1번째는 miji입니다.


## PANDAS

### Series 1차원 

In [146]:
import pandas as pd
animals=['Tigers','Bears','Cat']
p=pd.Series(animals)
print(p)
print(type(p)) 

0    Tigers
1     Bears
2       Cat
dtype: object
<class 'pandas.core.series.Series'>


In [148]:
d={'a':1,'b':2,'c':3}
print(d)
d_1=pd.Series(d) #인덱스부분에 문자열이 들어갈 수 있음
print(d_1)
print(d_1['a'])

{'a': 1, 'b': 2, 'c': 3}
a    1
b    2
c    3
dtype: int64
1


### DataFrame

In [149]:
#만들기

In [153]:
df=pd.DataFrame(np.arange(6).reshape(2,3))
df

0  1  2
0  0  1  2
1  3  4  5

In [154]:
type(df)

pandas.core.frame.DataFrame

In [155]:
pd.DataFrame({'a':[1,2],'b':2,'c':3})

a  b  c
0  1  2  3
1  2  2  3

In [161]:
pd.DataFrame([4,5,6,7], index=['a','b','c','d'],columns=['A'])

A
a  4
b  5
c  6
d  7

In [169]:
p=pd.DataFrame(np.arange(16).reshape(4,4),
               index=['a','b','c','d'],columns=['A','B','C','F'])
p

A   B   C   F
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15

In [190]:
df= pd.DataFrame([[15,'남','남중'],
                 [17,'여','여중']],
                 index=['철수','영희'], 
                 columns=['나이','성별','학교']
                )
print(df)
print(df.index)
print(df.columns)

    나이 성별  학교
철수  15  남  남중
영희  17  여  여중
Index(['철수', '영희'], dtype='object')
Index(['나이', '성별', '학교'], dtype='object')


In [179]:
# 삭제

df.drop('철수', inplace=True )

나이 성별  학교
영희  17  여  여중

In [212]:
df=pd.DataFrame([
    [15,'남','남중'],
    [17,'여','여중']],
    index=['철수','영희'],
    columns=['나이','성별','학교'])        
df

나이 성별  학교
철수  15  남  남중
영희  17  여  여중

In [194]:
df = pd.DataFrame([[90,98,85,100],[80,89,95,90],[70,95,100,90]],
                 index = ['서준','우현','인아'],
                 columns=['수학','영어','음악','체육']) 
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [214]:
df = pd.DataFrame({'수학': [90, 80, 70], '영어' : [98,89, 95], 
                  '음악':[85, 95, 100], '체육' : [100, 90, 90]},index =['서준','우현','인아']) 
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [204]:
a= df.values #numpy의 array로 바꿔서 보여줌
print(a) 
print(a[0,0])
print(a[1,:])

[[ 90  98  85 100]
 [ 80  89  95  90]
 [ 70  95 100  90]]
90
[80 89 95 90]


In [209]:
df.iloc[0,0] #numpy로 df.value하던가, df.iloc 를 붙이던가 

90

### 행 선택

In [228]:
#print(df.iloc[0,:]) # iloc = integer location
df.loc[['서준','우현'],:]  #loc = location
#print(type(df.iloc[[0,1] ,:]))

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [231]:
df.loc[:,['수학','영어']]

수학  영어
서준  90  98
우현  80  89
인아  70  95

In [232]:
df.loc[:,['수학']]

수학
서준  90
우현  80
인아  70

In [239]:
df.loc['서준'] #
df.iloc[[1]]

수학  영어  음악  체육
우현  80  89  95  90

## 이름 바꾸기 

In [242]:
df.index

Index(['서준', '우현', '인아'], dtype='object')

In [247]:
df.index=['준','현','인아']
df.index

Index(['준', '현', '인아'], dtype='object')

In [256]:
df.columns=['수학','영어','음악','체육']
df.columns

Index(['수학', '영어', '음악', '체육'], dtype='object')

In [258]:
df.rename(columns={'체육':'체'}, inplace = True)
df

수학  영어   음악    체
준   90  98   85  100
현   80  89   95   90
인아  70  95  100   90

## 연습

In [3]:
import plotly.express as px 
df= px.data.gapminder()
df

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [8]:
df_2=df[['country','continent']]
df_2.rename(columns={'country':'나라','continent':'대륙'}, inplace = True) 
df_2

C:\Users\user\AppData\Local\Temp\ipykernel_9880\1778590958.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.rename(columns={'country':'나라','continent':'대륙'}, inplace = True)


나라      대륙
0     Afghanistan    Asia
1     Afghanistan    Asia
2     Afghanistan    Asia
3     Afghanistan    Asia
4     Afghanistan    Asia
...           ...     ...
1699     Zimbabwe  Africa
1700     Zimbabwe  Africa
1701     Zimbabwe  Africa
1702     Zimbabwe  Africa
1703     Zimbabwe  Africa

[1704 rows x 2 columns]

In [7]:
df[df.year>1999]

country continent  year  lifeExp       pop    gdpPercap iso_alpha  \
10    Afghanistan      Asia  2002   42.129  25268405   726.734055       AFG   
11    Afghanistan      Asia  2007   43.828  31889923   974.580338       AFG   
22        Albania    Europe  2002   75.651   3508512  4604.211737       ALB   
23        Albania    Europe  2007   76.423   3600523  5937.029526       ALB   
34        Algeria    Africa  2002   70.994  31287142  5288.040382       DZA   
...           ...       ...   ...      ...       ...          ...       ...   
1679  Yemen, Rep.      Asia  2007   62.698  22211743  2280.769906       YEM   
1690       Zambia    Africa  2002   39.193  10595811  1071.613938       ZMB   
1691       Zambia    Africa  2007   42.384  11746035  1271.211593       ZMB   
1702     Zimbabwe    Africa  2002   39.989  11926563   672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143   469.709298       ZWE   

      iso_num  
10          4  
11          4  
22          8  
23          8  
34         12  
...       ...  
1679      887  
1690      894  
1691      894  
1702      716  
1703      716  

[284 rows x 8 columns]

In [299]:
#100- 500번째 뽑기 
df = df.iloc[[100,200,300,400,500]]
df.iloc[:,:5]

country continent  year  lifeExp       pop
100      Bangladesh      Asia  1972   45.252  70759295
200    Burkina Faso    Africa  1992   50.260   8878303
300        Colombia  Americas  1952   50.643  12350771
400  Czech Republic    Europe  1972   70.290   9862158
500         Eritrea    Africa  1992   49.991   3668440

In [300]:
df.columns
df.drop(['gdpPercap','iso_alpha','iso_num'], axis=1, inplace=True)
df

C:\Users\user\AppData\Local\Temp\ipykernel_8580\3216310912.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['gdpPercap','iso_alpha','iso_num'], axis=1, inplace=True)


country continent  year  lifeExp       pop
100      Bangladesh      Asia  1972   45.252  70759295
200    Burkina Faso    Africa  1992   50.260   8878303
300        Colombia  Americas  1952   50.643  12350771
400  Czech Republic    Europe  1972   70.290   9862158
500         Eritrea    Africa  1992   49.991   3668440

In [302]:
pd.DataFrame(pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['A']))


A
0  4
1  5
2  6
3  7

In [304]:
pd.DataFrame(pd.Series({"United Kingdom":"London", "India":"New Delhi",
"United States":"Washington", "Belgium":"Brussels"}))

0
United Kingdom      London
India            New Delhi
United States   Washington
Belgium           Brussels