In [15]:
import numpy as np
import pandas as pd

In [75]:
mpg= pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv')
mpg[:2]

mpg  cylinders  displacement  horsepower  weight  acceleration  model-year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70

In [76]:
mpg.columns=mpg.columns.str.capitalize()
mpg[:2]

Mpg  Cylinders  Displacement  Horsepower  Weight  Acceleration  Model-year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70

In [77]:
#칼럼 알파벳 순 정렬 
mpg= mpg[sorted(mpg.columns)]  #mpg로 [] 안묶으면 칼럼명만 정렬, 값은 그대로  
mpg[:2]

Acceleration  Cylinders  Displacement  Horsepower  Model-year   Mpg  Weight
0          12.0          8         307.0       130.0          70  18.0    3504
1          11.5          8         350.0       165.0          70  15.0    3693

In [79]:
employ=pd.read_csv('https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/e38afe62e088394d61ed30884dd50a6826eee0a8/employees.csv')
employ[:2]

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          198     Donald  OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1          199    Douglas     Grant    DGRANT  650.507.9844  13-JAN-08   

     JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID  
0  SH_CLERK    2600             -         124             50  
1  SH_CLERK    2600             -         124             50

In [80]:
#employee id 200 이상, salary 5000 넘는 사람의 수 
employ[(employ['EMPLOYEE_ID']>=200)&(employ['SALARY']>5000)].__len__()

6

In [81]:
employ[(employ.EMPLOYEE_ID>=200)&(employ.SALARY>5000)].__len__()

6

In [82]:
employ[(employ['EMPLOYEE_ID']>=200)&(employ['SALARY']>5000)].count()

EMPLOYEE_ID       6
FIRST_NAME        6
LAST_NAME         6
EMAIL             6
PHONE_NUMBER      6
HIRE_DATE         6
JOB_ID            6
SALARY            6
COMMISSION_PCT    6
MANAGER_ID        6
DEPARTMENT_ID     6
dtype: int64

In [83]:
arr=np.arange(1,21)
arr
arr.cumsum() #누적합 

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210])

In [99]:
#1-100 랜덤 10개의 배열(np.random 사용 ) 을 만들고 두개의 최대를 갖고있는 새로운 배열 
import random
a=np.random.randint(1,101,10)
b=np.random.randint(1,101,10)
np.maximum(a,b)


array([84, 29, 45, 45, 85,  7, 78, 52, 90, 63])

In [141]:
ti=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
ti[:2]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [132]:
ti[ti['Ticket'].str.contains('^P.+')]
ti['Ticket'].str.contains('^P.+').sum()


65

In [128]:
#Mrs. 찾기 [.]온전한 점 
ti[ti['Name'].str.contains('.+Mrs[.].+')].count()

PassengerId    125
Survived       125
Pclass         125
Name           125
Sex            125
Age            108
SibSp          125
Parch          125
Ticket         125
Fare           125
Cabin           44
Embarked       124
dtype: int64

In [133]:
#처음 ti묶은거 빼야댐 sum쓸려면 
ti['Name'].str.contains('.+Mrs[.].+').sum()

125

In [139]:
ti.rename(columns={'Survived':'생존'},inplace=True)
ti.head(1)

PassengerId  생존  Pclass                     Name   Sex   Age  SibSp  Parch  \
0            1   0       3  Braund, Mr. Owen Harris  male  22.0      1      0   

      Ticket  Fare Cabin Embarked  
0  A/5 21171  7.25   NaN        S

In [163]:
#평균 70, 표준편차 8인 25명의 수학점수 
math=np.random.randn(25)*8+70
math.round(2)
#np.random.normal(70,8,25) #정규분포 방법 

array([79.64, 61.03, 65.76, 73.18, 74.08, 62.71, 67.95, 71.36, 78.14,
       69.67, 65.64, 68.67, 63.82, 57.07, 77.29, 58.44, 77.97, 54.81,
       78.05, 75.46, 52.04, 80.51, 66.58, 75.3 , 61.77])

In [161]:
#55점 미만 
(math<55).sum()
len(math[math<55])
np.where(math<55).__len__()

1

In [180]:
np.random.RandomState(1234)
scores=np.random.randint(8,11,(2,10))
scores

array([[10, 10, 10,  9,  9, 10,  8, 10, 10,  9],
       [10,  9, 10,  9,  8,  9,  9,  8,  8,  8]])

In [188]:
arr=scores.cumsum(axis=1) #행기준 합 
arr

array([[10, 20, 30, 39, 48, 58, 66, 76, 86, 95],
       [10, 19, 29, 38, 46, 55, 64, 72, 80, 88]])

In [199]:
#데이터 프레임 만들기 
df=pd.DataFrame(scores,index=['A','B'],columns=range(1,11))
df['총점']=scores.sum(axis=1)
df

1   2   3  4  5   6  7   8   9  10  총점
A  10  10  10  9  9  10  8  10  10   9  95
B  10   9  10  9  8   9  9   8   8   8  88

In [207]:
x=np.array([1,2,3])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [263]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3=pd.Series(sdata) #키가 인덱스로 들어감 , 데이터프레임-> 칼럼명 

In [264]:
states=['California','Ohio','Oregon','Texas']
obj4=pd.Series(sdata,index=states)
obj4 #인덱스 있는 부분만 추출 

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [265]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [221]:
#값의 유무
'Ohio' in sdata

True

In [254]:
pd.notnull(s)

Ohio     True
Texas    True
dtype: bool

In [260]:
obj3+obj4

Ohio     NaN
Oregon   NaN
Texas    NaN
Utah     NaN
states   NaN
dtype: float64

In [275]:
obj4.name ='population'
obj4.index.name='state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [289]:
obj4=['Bob','Steve','Jeff','Ryan']
obj4

['Bob', 'Steve', 'Jeff', 'Ryan']

In [291]:
s= pd.Series([2,4,6,8])
s

0    2
1    4
2    6
3    8
dtype: int64

In [294]:
s= pd.Series([2,4,6,8],index=['a','b','c','d'])
s

a    2
b    4
c    6
d    8
dtype: int64

In [302]:
s.index=['a','b','c','d']
s

a    2
b    4
c    6
d    8
dtype: int64

In [296]:
di={'a':2,'b':4,'c':6, 'd':8}
di

{'a': 2, 'b': 4, 'c': 6, 'd': 8}

In [300]:
s['c']

6

In [522]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 

frame= pd.DataFrame(data)
frame.head()


state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [306]:
#순서지정 
pd.DataFrame(data, columns=['year','states','pop']) #y,s,p순서대로 자료가 정렬 

year states  pop
0  2000    NaN  1.5
1  2001    NaN  1.7
2  2002    NaN  3.6
3  2001    NaN  2.4
4  2002    NaN  2.9
5  2003    NaN  3.2

In [334]:
s=pd.Series([2,4,6,8], index=['a','b','c','d'])
s['e']=2
s

a    2
b    4
c    6
d    8
e    2
dtype: int64

In [321]:
s.value_counts() #값을 세는 것, index x 

2    2
4    1
6    1
8    1
dtype: int64

In [323]:
s.values 

array([2, 4, 6, 8, 2], dtype=int64)

In [338]:
a=s.astype('str') #데이터 타입 문자열로 바꾸기
list(map(str,s)) 

['2', '4', '6', '8', '2']

In [339]:
a*10

a    2222222222
b    4444444444
c    6666666666
d    8888888888
e    2222222222
dtype: object

In [341]:
list(map(lambda x:x*10,s )) #문자열 연산

[20, 40, 60, 80, 20]

In [342]:
s.info()

<class 'pandas.core.series.Series'>
Index: 5 entries, a to e
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 252.0+ bytes


In [352]:
s[s.isin([2,4])]

a    2
b    4
e    2
dtype: int64

In [368]:
frame[frame['state'].isin(['Ohio','Nevada'])]

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [524]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [ ]:
frame2=pd.DataFrame()

In [526]:
frame['eastern'] = np.where(frame["state"] =='Ohio' ,'yes','no') 
frame

state  year  pop eastern
0    Ohio  2000  1.5     yes
1    Ohio  2001  1.7     yes
2    Ohio  2002  3.6     yes
3  Nevada  2001  2.4      no
4  Nevada  2002  2.9      no
5  Nevada  2003  3.2      no

In [411]:
pop={'Naveda':{2001:2.4,2002:2.9}, 'Ohio':{2001:2.4,2001:17,2002:3.6}}
pop

{'Naveda': {2001: 2.4, 2002: 2.9}, 'Ohio': {2001: 17, 2002: 3.6}}

In [528]:
frame['eastern'] = np.where(frame["state"] .str.contains('Ohi') ,'yes','no') 
frame

state  year  pop eastern
0    Ohio  2000  1.5     yes
1    Ohio  2001  1.7     yes
2    Ohio  2002  3.6     yes
3  Nevada  2001  2.4      no
4  Nevada  2002  2.9      no
5  Nevada  2003  3.2      no

In [420]:
frame3=pd.DataFrame(pop)
frame3.index.name='인덱스'
frame3.columns.name='칼럼'
frame3

칼럼    Naveda  Ohio
인덱스               
2001     2.4  17.0
2002     2.9   3.6

## 색인 index

In [440]:
obj= pd.Series(range(3),index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [441]:
obj.index
obj.index[1]
'a' in obj.index
frame3.columns

Index(['Naveda', 'Ohio'], dtype='object', name='칼럼')

In [442]:
obj['d']=10
obj.index=['a','b','c','a']


In [443]:
obj['a'] #index 중복 값 허용 

a     0
a    10
dtype: int64

### reindex

In [448]:
obj= pd.Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])
print(obj)
obj2=obj.reindex(['a','b','c','d','e'])
obj2
obj3.uniqu

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64


a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [491]:
obj3=pd.Series(['blue','purple','yellow'], index=[0,2,4])
print(obj3)
obj3.reindex(range(6),method='ffill')
obj3.is_unique

0      blue
2    purple
4    yellow
dtype: object


True

In [462]:
obj=obj.reindex(['a','b','c','d']) 
obj['c':'d'] #c, d만 출력 [c:d] 시작점 끝점을 포함 

c    3.6
d    4.5
dtype: float64

In [463]:
obj['a':'c']=3.0 슬라이싱으로 값 변경 

In [474]:
df[0:1:]

1   2   3  4  5   6  7   8   9  10  총점
A  10  10  10  9  9  10  8  10  10   9  95

In [482]:
df=pd.DataFrame(np.arange(1,17).reshape(4,4))
np.where(df<=6,0,df)

array([[ 0,  0,  0,  0],
       [ 0,  0,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [486]:
frame3.index.name='year'
frame3.columns.name='state'
frame3

state  Naveda  Ohio
year               
2001      2.4  17.0
2002      2.9   3.6

In [487]:
frame3.values

array([[ 2.4, 17. ],
       [ 2.9,  3.6]])

In [511]:
df1=pd.DataFrame(np.arange(1,17).reshape(4,4),index=['a','b','c','d'], columns=['Ohio','Cali','Texas','NY'])
print (df1)
df2=df1.reindex(['a','b','c','d','e'])
df2


   Ohio  Cali  Texas  NY
a     1     2      3   4
b     5     6      7   8
c     9    10     11  12
d    13    14     15  16


Ohio  Cali  Texas    NY
a   1.0   2.0    3.0   4.0
b   5.0   6.0    7.0   8.0
c   9.0  10.0   11.0  12.0
d  13.0  14.0   15.0  16.0
e   NaN   NaN    NaN   NaN

In [506]:
df1=pd.DataFrame(np.arange(1,17).reshape(4,4),index=['a','b','c','d'], columns=['Ohio','Cali','Texas','NY'])
states=['Texas','유타','Ohio']
df1.reindex(columns=states)



Texas  유타  Ohio
a      3 NaN     1
b      7 NaN     5
c     11 NaN     9
d     15 NaN    13

In [514]:
fruit=pd.Series(['apple','banana','orange'], index=[0,2,4])
print(obj3)
fruit.reindex(range(6),method='ffill')


0     apple
2    banana
4    orange
dtype: object


<bound method Series.unique of 0     apple
2    banana
4    orange
dtype: object>

In [517]:
fruit.values

array(['apple', 'banana', 'orange'], dtype=object)