In [4]:
import numpy as np
import pandas as pd 
a=np.array([[2,1,6],[0,7,4],[5,3,2]])
np.sort(a,axis=0)

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [11]:
b=np.arange(0,6)
b=np.vstack([b,b+10,b+20,b+30,b+40,b+50])
b


array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [18]:
b=np.arange(6)+np.vstack([0,10,20,30,40,50])
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [14]:
#broadcasting
a=np.arange(0,6)
b=np.array([[0],[10],[20],[30],[40],[50]])
a+b 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [19]:
b[np.where(b%2==1)] 

array([ 1,  3,  5, 11, 13, 15, 21, 23, 25, 31, 33, 35, 41, 43, 45, 51, 53,
       55])

In [21]:
b[:,1::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25],
       [31, 33, 35],
       [41, 43, 45],
       [51, 53, 55]])

In [26]:
df=pd.DataFrame([['cat','mango'],['dog','orange'],['lion','melon']],
                columns=['animal','fruit'])
df

animal   fruit
0    cat   mango
1    dog  orange
2   lion   melon

In [41]:
#mango melon 뽑기 
print( df.iloc[[0,2],[1]] ) 
print( df.fruit.iloc[[0,2]] )
df.loc[[0,2],['fruit']]

   fruit
0  mango
2  melon
0    mango
2    melon
Name: fruit, dtype: object


fruit
0  mango
2  melon

In [42]:
df.values[::2, 1:2] 

array([['mango'],
       ['melon']], dtype=object)

In [44]:
df = pd.DataFrame([['John',25,'student'],['Cho',30,'teacher']],
                           columns= ['Name','Age','Job']) 
df

Name  Age      Job
0  John   25  student
1   Cho   30  teacher

In [55]:
print (df.loc[:,['Name','Job']])
print( df[['Name','Job'] ]  )

   Name      Job
0  John  student
1   Cho  teacher
   Name      Job
0  John  student
1   Cho  teacher


In [ ]:
#np.min, np.argmin 
min최솟값 , argmin은 최솟값의 인덱스 

In [59]:
a = np.array([[3,5,1],[2,4,6]])
print(a )
print(np.min(a)) #= 1
print(np.argmin(a)) #1의 인덱스= 2

[[3 5 1]
 [2 4 6]]
1
2


In [120]:
#0-24 랜덤 행열 만들기 
import random
li= list(range(25))
random.shuffle(li)
c=np.array(li).reshape(5,5)
print(c)

a=np.array(random.sample(range(25), 25)).reshape(5, 5) 
print(a)

print(np.random.randint(0,25,(5,5)))

print (np.random.permutation(25).reshape(5,5))

[[ 9 11  0  2  7]
 [ 6 24  1 22 17]
 [18  4 10 14 20]
 [12 15 19 16 23]
 [21 13  5  3  8]]
[[14 23  2 22 12]
 [ 6  1  9 18  7]
 [ 8 13 16 11  5]
 [ 4 15 20 17 21]
 [ 0  3 19 10 24]]
[[ 5  5 19  0  8]
 [ 3  7  6  1 10]
 [22  6 10 13 11]
 [ 7 22  7 15 14]
 [18 19  1 15 21]]
[[19 20  2 10 22]
 [21  5 24  8 18]
 [15  4 12 11  9]
 [16  6  0  7  1]
 [23 17  3 14 13]]


In [129]:
random.seed(1234)
print(a)
np.max(a)

np.max(a, axis=-1)


[[14 23  2 22 12]
 [ 6  1  9 18  7]
 [ 8 13 16 11  5]
 [ 4 15 20 17 21]
 [ 0  3 19 10 24]]


array([23, 18, 16, 21, 24])

In [130]:
df = pd.DataFrame([[90,98,95,100],[80,89,95,90],[60,65,80,90]],
                 index=['서준','우현','인아'],
                 columns=['수학','영어','음악','체육'])
df 

수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90
인아  60  65  80   90

In [144]:
#서준이 부정행위로 0 점
df.loc[['서준']]=0
df
df.iloc[0]=0
df
df[:1]=0 #슬라이싱 
df

수학  영어  음악  체육
서준   0   0   0   0
우현  80  89  95  90
인아  60  65  80  90

In [188]:
import plotly.express as px
df= px.data.gapminder() 
df.info()
df[:2]


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    1704 non-null   object 
 1   continent  1704 non-null   object 
 2   year       1704 non-null   int64  
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64  
 5   gdpPercap  1704 non-null   float64
 6   iso_alpha  1704 non-null   object 
 7   iso_num    1704 non-null   int64  
dtypes: float64(2), int64(3), object(3)
memory usage: 106.6+ KB


country continent  year  lifeExp      pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801  8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332  9240934  820.853030       AFG   

   iso_num  
0        4  
1        4

In [165]:
#country, continent만 뽑기
df[['continent','country']]
df.iloc[:,:2]
df.loc[:,['country','continent']]

country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
1699     Zimbabwe    Africa
1700     Zimbabwe    Africa
1701     Zimbabwe    Africa
1702     Zimbabwe    Africa
1703     Zimbabwe    Africa

[1704 rows x 2 columns]

In [186]:
#나라 , 대륙으로 rename 
df.rename(columns={'country':'나라','continent':'대륙'}, inplace = True)
df

나라      대륙  year  lifeExp       pop
0     Afghanistan    Asia  1952   28.801   8425333
1     Afghanistan    Asia  1957   30.332   9240934
2     Afghanistan    Asia  1962   31.997  10267083
3     Afghanistan    Asia  1967   34.020  11537966
4     Afghanistan    Asia  1972   36.088  13079460
...           ...     ...   ...      ...       ...
1699     Zimbabwe  Africa  1987   62.351   9216418
1700     Zimbabwe  Africa  1992   60.377  10704340
1701     Zimbabwe  Africa  1997   46.809  11404948
1702     Zimbabwe  Africa  2002   39.989  11926563
1703     Zimbabwe  Africa  2007   43.487  12311143

[1704 rows x 5 columns]

In [189]:
df=df.drop(['gdpPercap','iso_alpha','iso_num'],axis=1)
df


country continent  year  lifeExp       pop
0     Afghanistan      Asia  1952   28.801   8425333
1     Afghanistan      Asia  1957   30.332   9240934
2     Afghanistan      Asia  1962   31.997  10267083
3     Afghanistan      Asia  1967   34.020  11537966
4     Afghanistan      Asia  1972   36.088  13079460
...           ...       ...   ...      ...       ...
1699     Zimbabwe    Africa  1987   62.351   9216418
1700     Zimbabwe    Africa  1992   60.377  10704340
1701     Zimbabwe    Africa  1997   46.809  11404948
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[1704 rows x 5 columns]

In [190]:
df.iloc[:,:-3]

country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
1699     Zimbabwe    Africa
1700     Zimbabwe    Africa
1701     Zimbabwe    Africa
1702     Zimbabwe    Africa
1703     Zimbabwe    Africa

[1704 rows x 2 columns]

In [198]:
#2002년 이후 
df[df['year']>=2002]
df[df.year>=2002]

country continent  year  lifeExp       pop
10    Afghanistan      Asia  2002   42.129  25268405
11    Afghanistan      Asia  2007   43.828  31889923
22        Albania    Europe  2002   75.651   3508512
23        Albania    Europe  2007   76.423   3600523
34        Algeria    Africa  2002   70.994  31287142
...           ...       ...   ...      ...       ...
1679  Yemen, Rep.      Asia  2007   62.698  22211743
1690       Zambia    Africa  2002   39.193  10595811
1691       Zambia    Africa  2007   42.384  11746035
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[284 rows x 5 columns]

In [214]:
df_1=pd.DataFrame([[20,'AB','서울'], [25,'B','강원'],[27,'A','경기']], 
             index=['길동','춘향','몽룡'],
            columns=['이름','혈액형','거주지'])
df_1
#춘향 몽룡만 뽑기
print(  df_1.iloc[[1,2],:])
#거주지 -> 출생지 이름바꾸기 
df_1.rename(columns={'거주지':'출생지'})
df_1.columns=['이름','혈액형','출생지']

    이름 혈액형 거주지
춘향  25   B  강원
몽룡  27   A  경기


## 행추가

In [236]:
df = pd.DataFrame([[90,98,95,100],[80,89,95,90],[60,65,80,90]],
                 index=['서준','우현','인아'],
                 columns=['수학','영어','음악','체육'])
#없으면 만들고 있으면 덮어쓴다. 
df.loc['상기']= [95,100,80,95]
df

수학   영어  음악   체육
서준  90   98  95  100
우현  80   89  95   90
인아  60   65  80   90
상기  95  100  80   95

In [237]:
df.loc['인아']= [95,100,80,95]
df

수학   영어  음악   체육
서준  90   98  95  100
우현  80   89  95   90
인아  95  100  80   95
상기  95  100  80   95

In [239]:

#원소 조회 
print(df.iloc[2,3])
print(df.iloc[2][3])


95
95


수학   영어  음악   체육
서준  90   98  95  100
우현  80   89  95   90
인아  95  100  80   95
상기  95  100  80   95

In [224]:
#원소값 바꾸기
#원소 선택 = 새로운 값, 여러개 바꾸기 
df.loc["인아",["체육","영어"]]=80,90
df

수학   영어  음악   체육   미술
서준  90   98  95  100   80
우현  80   89  95   90   90
인아  95   90  80   80   95
상기  95  100  80   95  100

In [307]:
#csv
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv')
#웹주소 가능 대신 그냥 주소아니고 깃허브일 경우 raw눌러서 그 사이트 
df.to_csv('filename.csv')
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [281]:
#displacement -> displ
df.rename(columns={'displacement':'displ', 'model-year':'year'}, inplace=True)
df

mpg  cylinders  displ  horsepower  weight  acceleration  year
0    18.0          8  307.0       130.0    3504          12.0    70
1    15.0          8  350.0       165.0    3693          11.5    70
2    18.0          8  318.0       150.0    3436          11.0    70
3    16.0          8  304.0       150.0    3433          12.0    70
4    17.0          8  302.0       140.0    3449          10.5    70
..    ...        ...    ...         ...     ...           ...   ...
393  27.0          4  140.0        86.0    2790          15.6    82
394  44.0          4   97.0        52.0    2130          24.6    82
395  32.0          4  135.0        84.0    2295          11.6    82
396  28.0          4  120.0        79.0    2625          18.6    82
397  31.0          4  119.0        82.0    2720          19.4    82

[398 rows x 7 columns]

In [282]:
df[df.year>=70]

mpg  cylinders  displ  horsepower  weight  acceleration  year
0    18.0          8  307.0       130.0    3504          12.0    70
1    15.0          8  350.0       165.0    3693          11.5    70
2    18.0          8  318.0       150.0    3436          11.0    70
3    16.0          8  304.0       150.0    3433          12.0    70
4    17.0          8  302.0       140.0    3449          10.5    70
..    ...        ...    ...         ...     ...           ...   ...
393  27.0          4  140.0        86.0    2790          15.6    82
394  44.0          4   97.0        52.0    2130          24.6    82
395  32.0          4  135.0        84.0    2295          11.6    82
396  28.0          4  120.0        79.0    2625          18.6    82
397  31.0          4  119.0        82.0    2720          19.4    82

[398 rows x 7 columns]

In [283]:
df.year=df.year+1900
df

mpg  cylinders  displ  horsepower  weight  acceleration  year
0    18.0          8  307.0       130.0    3504          12.0  1970
1    15.0          8  350.0       165.0    3693          11.5  1970
2    18.0          8  318.0       150.0    3436          11.0  1970
3    16.0          8  304.0       150.0    3433          12.0  1970
4    17.0          8  302.0       140.0    3449          10.5  1970
..    ...        ...    ...         ...     ...           ...   ...
393  27.0          4  140.0        86.0    2790          15.6  1982
394  44.0          4   97.0        52.0    2130          24.6  1982
395  32.0          4  135.0        84.0    2295          11.6  1982
396  28.0          4  120.0        79.0    2625          18.6  1982
397  31.0          4  119.0        82.0    2720          19.4  1982

[398 rows x 7 columns]

In [457]:
df.to_csv('mpg.csv')

In [287]:
pd.read_clipboard() 

mpg,cylinders,displacement,horsepower,weight,acceleration,model-year
0                              18,8,307,130,3504,12,70                  
1                            15,8,350,165,3693,11.5,70                  
2                              18,8,318,150,3436,11,70                  
3                              16,8,304,150,3433,12,70                  
4                            17,8,302,140,3449,10.5,70                  
..                                                 ...                  
393                           27,4,140,86,2790,15.6,82                  
394                            44,4,97,52,2130,24.6,82                  
395                           32,4,135,84,2295,11.6,82                  
396                           28,4,120,79,2625,18.6,82                  
397                           31,4,119,82,2720,19.4,82                  

[398 rows x 1 columns]

In [288]:
import os
os.getcwd()

'C:\\Users\\user\\test'

In [305]:
df=pd.read_excel('.././Downloads/Presidents.xlsx')
df

President  Years in office  Year first inaugurated  \
0        George Washington              8.0                    1789   
1               John Adams              4.0                    1797   
2         Thomas Jefferson              8.0                    1801   
3            James Madison              8.0                    1809   
4             James Monroe              8.0                    1817   
5        John Quincy Adams              4.0                    1825   
6           Andrew Jackson              8.0                    1829   
7        Martin Van Buren               4.0                    1837   
8   William Henry Harrison              0.8                    1841   
9            James K. Polk              4.0                    1845   
10          Zachary Taylor              1.0                    1849   
11         Franklin Pierce              4.0                    1853   
12          James Buchanan              4.0                    1857   
13         Abraham Lincoln              4.0                    1861   
14        Ulysses S. Grant              8.0                    1869   
15     Rutherford B. Hayes              4.0                    1877   
16       James A. Garfield              0.5                    1881   
17        Grover Cleveland              4.0                    1885   
18       Benjamin Harrison              4.0                    1889   
19        Grover Cleveland              4.0                    1893   
20        William McKinley              4.0                    1897   
21     William Howard Taft              4.0                    1909   
22          Woodrow Wilson              8.0                    1913   
23       Warren G. Harding              2.0                    1921   
24          Herbert Hoover              4.0                    1929   
25      Franklin Roosevelt             12.0                    1933   
26    Dwight D. Eisenhower              8.0                    1953   
27         John F. Kennedy              3.0                    1961   
28        Richard M. Nixon              5.0                    1969   
29            Jimmy Carter              4.0                    1977   
30           Ronald Reagan              8.0                    1981   
31             George Bush              4.0                    1989   
32            Bill Clinton              8.0                    1993   
33          George W. Bush              8.0                    2001   
34            Barack Obama              NaN                    2009   

    Age at inauguration State elected from  # of electoral votes  \
0                    57           Virginia                    69   
1                    61      Massachusetts                   132   
2                    57           Virginia                    73   
3                    57           Virginia                   122   
4                    58           Virginia                   183   
5                    57      Massachusetts                    84   
6                    61          Tennessee                   178   
7                    54           New York                   170   
8                    68               Ohio                   234   
9                    49          Tennessee                   170   
10                   64          Louisiana                   163   
11                   48      New Hampshire                   254   
12                   65       Pennsylvania                   174   
13                   52           Illinois                   180   
14                   46           Illinois                   214   
15                   54               Ohio                   185   
16                   49               Ohio                   214   
17                   47           New York                   219   
18                   55            Indiana                   233   
19                   55           New York                   277   
20                   54         

In [303]:
!pip install openpyxl

     -------------------------------------- 250.0/250.0 kB 7.7 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [315]:
df.head(2)
df.describe()
df.info() #자주 사용 
df.dtypes
df.shape #행과 열 
df.size
df.count()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    396 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model-year    398 non-null    int64  
dtypes: float64(4), int64(3)
memory usage: 21.9 KB


mpg             398
cylinders       398
displacement    398
horsepower      396
weight          398
acceleration    398
model-year      398
dtype: int64

In [325]:
#빈도수 
df.count()
df['cylinders'].value_counts()
df['cylinders'].unique()

array([8, 4, 6, 3, 5], dtype=int64)

In [326]:
df.mean()

mpg               23.514573
cylinders          5.454774
displacement     193.425879
horsepower       104.189394
weight          2970.424623
acceleration      15.568090
model-year        76.010050
dtype: float64

In [328]:
np.mean(df, axis =1)

0      578.428571
1      616.071429
2      573.000000
3      570.428571
4      570.928571
          ...    
393    449.228571
394    347.657143
395    377.657143
396    422.371429
397    436.771429
Length: 398, dtype: float64

In [332]:
df.corr()
df[['mpg','cylinders','displacement']].corr()

mpg  cylinders  displacement
mpg           1.000000  -0.775396     -0.804203
cylinders    -0.775396   1.000000      0.950721
displacement -0.804203   0.950721      1.000000

### 결측치

In [349]:
titanic= pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
titanic
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [472]:
titanic.head(2)

titanic.isnull().sum()


passengerid      0
survived         0
pclass           0
name             0
sex              0
age            177
sibsp            0
parch            0
ticket           0
fare             0
cabin          687
embarked         2
Pclass           0
dtype: int64

In [473]:
df1=titanic.copy()
df1

passengerid  survived  pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  name     sex   age  sibsp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     parch            ticket     fare cabin embarked Pclass  
0        0         A/5 21171   7.2500   NaN        S      3  
1        0          PC 17599  71.2833   C85        C      1  
2        0  STON/O2. 3101282   7.9250   NaN        S      3  
3        0            113803  53.1000  C123        S      1  
4        0            373450   8.0500   NaN        S      3  
..     ...               ...      ...   ...      ...    ...  
886      0            211536  13.0000   NaN        S      2  
887      0            112053  30.0000   B42        S      1  
888      2        W./C. 6607  23.4500   NaN        S      3  
889      0            111369  30.0000  C148        C      1  
890      0            370376   7.7500   NaN        Q      3  

[891 rows x 13 columns]

In [467]:
df1.dropna(axis=1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   weight        398 non-null    int64  
 4   acceleration  398 non-null    float64
 5   model-year    398 non-null    int64  
dtypes: float64(3), int64(3)
memory usage: 18.8 KB


In [470]:
df1

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [476]:
#v평균값으로 ㅐ체
mean_age=df1['age'].mean()
df1['age'].fillna(mean_age,inplace = True)
df1['age'].isnull()


0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [477]:
df1['age'].isnull().sum()

0

In [ ]:
df=Age.fill[]

## 중복데이터 

In [491]:
df=pd.DataFrame({'A':['a','a','b','a','b'], 'B':[1,1,1,2,2],
                                             'C':[1,1,2,2,2]})
df

A  B  C
0  a  1  1
1  a  1  1
2  b  1  2
3  a  2  2
4  b  2  2

In [492]:
print( df.duplicated())
df['A'].duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool


0    False
1     True
2    False
3     True
4     True
Name: A, dtype: bool

In [489]:
df.drop_duplicates(inplace=True)
df

A  B  C
0  a  1  1
2  b  1  2
3  a  2  2
4  b  2  2

In [495]:
E = pd.Series(['e0','e1','e2','e3'],name='e')
F = pd.Series(['f0','f1','f2'],name='f', index=[3,4,5])
G = pd.Series(['g0','g1','g2','g3'],name='g')
E

0    e0
1    e1
2    e2
3    e3
Name: e, dtype: object

In [497]:
print( pd.concat([E,F]))

pd.concat ([E,F], axis=1)

0    e0
1    e1
2    e2
3    e3
3    f0
4    f1
5    f2
dtype: object


e    f
0   e0  NaN
1   e1  NaN
2   e2  NaN
3   e3   f0
4  NaN   f1
5  NaN   f2

In [374]:
#합치기 
pd.concat([E,G],axis=1)

re  re
0  e0  g0
1  e1  g1
2  e2  g2
3  e3  g3

In [498]:
#DataFrame+FataFrame
df1= pd.DataFrame({'a':['a0','a1','a2'],'b':['b0','b1','b2'],'c':['c0','c1','c2']},index=[0,1,2])
df2= pd.DataFrame({'b':['b2','b3','b4'],'c':['c2','c3','c4'],'d':['d2','d3','d4']},index=[1,2,3])
print (pd.concat([df1,df2],axis=1))
print (pd.concat([df1,df2],axis=0, ignore_index=True)) #ignore_index -> index무시하고 순서정렬 
pd.concat([df1,df2],axis=0, join='inner')

     a    b    c    b    c    d
0   a0   b0   c0  NaN  NaN  NaN
1   a1   b1   c1   b2   c2   d2
2   a2   b2   c2   b3   c3   d3
3  NaN  NaN  NaN   b4   c4   d4
     a   b   c    d
0   a0  b0  c0  NaN
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b2  c2   d2
4  NaN  b3  c3   d3
5  NaN  b4  c4   d4


b   c
0  b0  c0
1  b1  c1
2  b2  c2
1  b2  c2
2  b3  c3
3  b4  c4

In [420]:
#칼럼이름 소문자로 바꾸기 
li = []
for i in titanic.columns:
    li.append(i.lower())
titanic.columns = li
titanic.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [418]:
titanic.columns=[i.lower() for i in titanic.columns]
titanic.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [417]:
titanic.columns = map(lambda x: x.lower(), list(titanic.columns)) 
titanic.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [422]:
titanic.columns.str.lower() #string 으로 바꾸면 바로 적용

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [429]:
titanic['name'].str.upper() #이름컬럼의 내용을 string으로 변환 후 대문자 

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...                        
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: name, Length: 891, dtype: object

In [ ]:
titanic['name'].str.contains("Mr") #보고싶으면 df이름으로 묶기 
#Mr 있는지 없는지 
titanic[titanic['name'].str.contains("Mrs")] #Mrs. 여자찾기 
titanic[titanic['name'].str.contains("^F.+")] #F로 시작하는 사람이름 찾기 

In [436]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
              ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]
all_data 

[['John', 'Emily', 'Michael', 'Mary', 'Steven'],
 ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

In [441]:
#중첩을 리스트에 하나로 담기 
names= [j for i in all_data for j in i]
names= all_data[0]+all_data[1] 

In [447]:
#e가 두번이상
[i for i in names if i.count('e')>=2]

['Steven']

In [454]:
np.random.randn(2,3)#stardard normal distribution 표준정규분포 , 평균 0, 분산=시그마 =1
np.random.randn(2,3)*3+80 #분산 3 , 평균 80인 수학점수 

array([[81.33178526, 78.06091531, 78.0753987 ],
       [81.56363964, 78.12610939, 81.77470867]])

In [450]:
np.random.rand(2,3) #0-1

array([[0.38846611, 0.44053128, 0.22376431],
       [0.90130454, 0.72569703, 0.74365318]])

In [464]:
titanic['Pclass']=titanic['pclass'].astype('str')
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   passengerid  891 non-null    int64  
 1   survived     891 non-null    int64  
 2   pclass       891 non-null    int64  
 3   name         891 non-null    object 
 4   sex          891 non-null    object 
 5   age          714 non-null    float64
 6   sibsp        891 non-null    int64  
 7   parch        891 non-null    int64  
 8   ticket       891 non-null    object 
 9   fare         891 non-null    float64
 10  cabin        204 non-null    object 
 11  embarked     889 non-null    object 
 12  Pclass       891 non-null    object 
dtypes: float64(2), int64(5), object(6)
memory usage: 90.6+ KB


In [538]:
em=pd.read_csv("https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/e38afe62e088394d61ed30884dd50a6826eee0a8/employees.csv")
em
em.isnull().sum()
em[['FIRST_NAME','LAST_NAME']] #name만 뽑기 , firstname, last name 


a.sort_values('SALARY',ascending=False)

EMPLOYEE_ID FIRST_NAME LAST_NAME    EMAIL  PHONE_NUMBER  HIRE_DATE  \
12          103  Alexander    Hunold  AHUNOLD  590.423.4567  03-JAN-06   
30          121       Adam     Fripp   AFRIPP  650.123.2234  10-APR-05   
24          115  Alexander      Khoo    AKHOO  515.127.4562  18-MAY-03   

      JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID  
12   IT_PROG    9000             -         102             60  
30    ST_MAN    8200             -         100             50  
24  PU_CLERK    3100             -         114             30

In [537]:
a= em[em['FIRST_NAME'].str.contains( '^A.+')]
a

EMPLOYEE_ID FIRST_NAME LAST_NAME    EMAIL  PHONE_NUMBER  HIRE_DATE  \
12          103  Alexander    Hunold  AHUNOLD  590.423.4567  03-JAN-06   
24          115  Alexander      Khoo    AKHOO  515.127.4562  18-MAY-03   
30          121       Adam     Fripp   AFRIPP  650.123.2234  10-APR-05   

      JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID  
12   IT_PROG    9000             -         102             60  
24  PU_CLERK    3100             -         114             30  
30    ST_MAN    8200             -         100             50