In [1]:
import sklearn
import pandas as pd

In [77]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [30]:
iris=load_iris()
iris_data= iris.data
iris_label=iris.target
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df

print(iris_label)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [146]:
iris=load_iris()
iris_data=iris.data
iris_label=iris.target
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [152]:
from sklearn.model_selection import GridSearchCV
x_train,x_test,y_train,y_test=train_test_split(iris_data,iris_label, 
                                               test_size=0.2,random_state=121)

dtree=DecisionTreeClassifier()
parameters={'max_depth':[1,2,3], 'min_samples_split': [2,3]}
grid_dtree=GridSearchCV(dtree,param_grid=parameters, cv=3, refit=True)
grid_dtree.fit(x_train, y_train)

scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df


mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000670      0.000474         0.000674        0.000477   
1       0.000000      0.000000         0.001002        0.000007   
2       0.000000      0.000000         0.001000        0.000002   
3       0.000663      0.000469         0.000000        0.000000   
4       0.000322      0.000455         0.000323        0.000457   
5       0.000332      0.000470         0.000665        0.000470   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [154]:
#GridsearchCV의 refit으로 이미 학습된 estimator 반환
estimator=grid_dtree.best_estimator_

#이미 학습되서 별도의 학습 필요없음
pred= estimator.predict(x_test)
accuracy_score(y_test,pred)

0.9666666666666667

In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
items=np.array(items).reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [145]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.9333333333333333

In [112]:
sum(y_test==pred)/len(y_test)

0.9333333333333333

In [45]:
iris= load_iris()
type(iris)

sklearn.utils._bunch.Bunch

In [48]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [55]:
!pip install pydataset

  Using cached pydataset-0.2.0-py3-none-any.whl


In [221]:
from pydataset import data
mpg=data('mpg')
mpg.head(3)

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact

In [222]:
x = mpg[['displ', 'cty', 'hwy','cyl']]
y = mpg['manufacturer'] 
y

1            audi
2            audi
3            audi
4            audi
5            audi
          ...    
230    volkswagen
231    volkswagen
232    volkswagen
233    volkswagen
234    volkswagen
Name: manufacturer, Length: 234, dtype: object

In [223]:



X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

df_clf=DecisionTreeClassifier(min_samples_split= 4, min_samples_leaf=2, max_depth=4)


In [224]:
df_clf.fit(X_train, y_train)


DecisionTreeClassifier(max_depth=4, min_samples_leaf=2, min_samples_split=4)

In [225]:
pred=df_clf.predict(X_test)

accuracy_score(y_test,pred)

0.352112676056338

In [210]:

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
dtree=DecisionTreeClassifier()

parameters={'min_samples_split':[1,2,3,4],'min_samples_leaf':[1,2], 'max_depth':[1,2,3,4,5,6,7]}
grid_dtree=GridSearchCV(dtree,param_grid=parameters, cv=3, refit=True)
grid_dtree.fit(X_train, y_train)

scores_df=pd.DataFrame(grid_dtree.cv_results_)
grid_dtree.best_params_
grid_dtree.best_score_

0.5580246913580247

In [45]:
iris_df= pd.DataFrame(iris['data'], columns =['sepal length (cm)','sepal width (cm)',
  'petal length (cm)', 'petal width (cm)']  )
iris_df['target']=iris.target

#칼럼값  바꾸기 숫자를 영어로 매핑 
iris_df['species']=iris_df['target'].apply(lambda x: 'setosa 'if x==0 else('versicolor'
                            if x==1 else 'virficana'))

iris_df['species'] = pd.Categorical.from_codes(iris_df['target'],load_iris()['target_names'])

iris_df['species'] = iris_df['target'].replace({0:'setosa',1:'versicolor',2:'virgicana'}) 
iris_df[:1]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   

   target species  
0       0  setosa

In [48]:
x= iris_df.iloc[:,:4]
y= iris_df['species']

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
df_clf=DecisionTreeClassifier()
df_clf.fit(X_train,y_train)

pred=df_clf.predict(X_test)

accuracy_score(y_test,pred)

0.9333333333333333

In [40]:
X_train.shape


(112, 4)

In [62]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]



0      1      2    3      4      5     6       7    8      9   \
0       0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
2       0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3     396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
4       0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
...         ...    ...    ...  ...    ...    ...   ...     ...  ...    ...   
1007  396.90000   5.64  23.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1008    0.10959   0.00  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
1009  393.45000   6.48  22.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1010    0.04741   0.00  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
1011  396.90000   7.88  11.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   

        10  
0     15.3  
1      NaN  
2     17.8  
3      NaN  
4     17.8  
...    ...  
1007   NaN  
1008  21.0  
1009   NaN  
1010  21.0  
1011   NaN  

[1012 rows x 11 columns]

In [72]:
from sklearn.datasets import load_diabetes
load_diabetes()

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [213]:
from sklearn.model_selection import KFold

In [84]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

len(X_train)
len(y_train)



163

In [90]:
iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

scores=cross_val_score(dt_clf,data,label, scoring='accuracy', cv=3 )
scores
np.mean(scores)

0.9666666666666667

In [215]:
import plotly.express as px
df = px.data.gapminder()
df 


country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [243]:
#train_test_split
x=df[['pop','iso_num','lifeExp','gdpPercap']]
y=df['country']
x_train,x_test,y_train,y_test=train_test_split(x,y)
dclf=DecisionTreeClassifier()
dclf.fit(x_train,y_train)
pred=dclf.predict(x_test)
accuracy_score(pred,y_test)

0.9788732394366197

In [246]:
#cross_val_score

x=df[['pop','iso_num','lifeExp','gdpPercap']]
y=df['country']
dt_clf=DecisionTreeClassifier()
scores=cross_val_score(dt_clf,x,y, scoring='accuracy', cv=3)
scores
np.mean(scores)

0.95481220657277

In [260]:
#gridsearchCV
xtrain,xtest,ytrain,ytest=train_test_split(x,y)
dtree=DecisionTreeClassifier()
p={'max_depth':[1,2,3],  'min_samples_split':[2,3]}
grid_dtree=GridSearchCV(dtree, param_grid=p, cv=3, refit=True)
grid_dtree.fit(xtrain,ytrain)
scores_df= pd.DataFrame(grid_dtree.cv_results_)
grid_dtree.best_score_

0.04773082942097027