### 문장 토큰화

In [9]:
import nltk
from nltk import sent_tokenize
nltk.download('punkt')
text_sample = 'Turn your wounds into wisdom.\
               Life is either a daring adventure or nothing at all.\
               The two most important days in your life are the day you are born and the day you find out why.' 
sent_tokenize(text_sample)

#반환된 리스트 3개의 문장으로 된 문자열 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['Turn your wounds into wisdom.',
 'Life is either a daring adventure or nothing at all.',
 'The two most important days in your life are the day you are born and the day you find out why.']

### 단어 토큰화 

In [23]:
#for문
from nltk import word_tokenize
words=[]
sent = sent_tokenize(text_sample)
for i in sent:
    words.append(word_tokenize(i)) 


#list comprehension
[word_tokenize(i) for i in sent]

[['Turn', 'your', 'wounds', 'into', 'wisdom', '.'],
 ['Life',
  'is',
  'either',
  'a',
  'daring',
  'adventure',
  'or',
  'nothing',
  'at',
  'all',
  '.'],
 ['The',
  'two',
  'most',
  'important',
  'days',
  'in',
  'your',
  'life',
  'are',
  'the',
  'day',
  'you',
  'are',
  'born',
  'and',
  'the',
  'day',
  'you',
  'find',
  'out',
  'why',
  '.']]

### Lemmatization 표제어 추출 
* 원형

In [21]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
li = ['swimming','swam','swum']
lemma = WordNetLemmatizer()
for i in li:
    print(lemma.lemmatize(i,"v")) 

swim
swim
swim


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


### 희소행렬
* COO

In [25]:
from scipy import sparse
import numpy as np
# 0 이 아닌 데이터 추출
data = np.array([3,1,2])

# 행 위치와 열 위치를 각각 array로 생성 
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

# sparse 패키지의 coo_matrix를 이용하여 COO 형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos,col_pos)))

print(type(sparse_coo))
print(sparse_coo)
dense01=sparse_coo.toarray()
print(type(dense01),"\n", dense01)

<class 'scipy.sparse._coo.coo_matrix'>
  (0, 0)	3
  (0, 2)	1
  (1, 1)	2
<class 'numpy.ndarray'> 
 [[3 0 1]
 [0 2 0]]


* CSR 

In [27]:
from scipy import sparse

dense2 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

# 0 이 아닌 데이터 추출
data2 = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

# 행 위치와 열 위치를 각각 array로 생성 
row_pos = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

# COO 형식으로 변환 
sparse_coo = sparse.coo_matrix((data2, (row_pos,col_pos)))

# 행 위치 배열의 고유한 값들의 시작 위치 인덱스를 배열로 생성
row_pos_ind = np.array([0, 2, 7, 9, 10, 12, 13])

# CSR 형식으로 변환 
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


### Word2Vec 실습

In [28]:
import nltk
nltk.download('movie_reviews')

from nltk.corpus import movie_reviews
sentences = [list(s) for s in movie_reviews.sents()]
sentences[0]

[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\movie_reviews.zip.


['plot',
 ':',
 'two',
 'teen',
 'couples',
 'go',
 'to',
 'a',
 'church',
 'party',
 ',',
 'drink',
 'and',
 'then',
 'drive',
 '.']

## 감성분석

In [40]:
text_sample = 'Turn your wounds into wisdom.\
               Life is either a daring adventure or nothing at all.\
               The two most important days in your life are the day you are born and the day you find out why.' 

In [42]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
senti_analyzer=SentimentIntensityAnalyzer()
senti_scores=senti_analyzer.polarity_scores(text_ sample)
senti_scores

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


{'neg': 0.0, 'neu': 0.751, 'pos': 0.249, 'compound': 0.8516}

### 코사인 유사도

In [45]:
np.array((1,2)).dot(np.array((2,1)))

4

In [47]:
#(3,4) , (1,2)의 코사인 유사도
(np.array((1,2))@np.array((3,4))) / (np.sqrt(5) * np.sqrt(25)) 

0.9838699100999074

In [56]:
p1 = np.array((1,2))
p2 = np.array((2,1))

def cosine_similarity(p1, p2):
        return (p1 @ p2) / (np.sqrt(sum(np.square(p1)))*np.sqrt(sum(np.square(p2))))
cosine_similarity(p1, p2) 

0.7999999999999998