In [1]:
import tensorflow as tf

In [2]:
x=tf.ones(shape=(2,1))

In [3]:
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [4]:
x=tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [5]:
x= tf.random.normal(shape=(3,1),mean=0,stddev=1.)

In [6]:
print(x)

tf.Tensor(
[[ 0.8146633]
 [-0.7450391]
 [-1.9143505]], shape=(3, 1), dtype=float32)


In [7]:
x=tf.random.uniform(shape=(3,1),minval=0., maxval=1.)

In [8]:
print(x)

tf.Tensor(
[[0.72333837]
 [0.6746836 ]
 [0.9563606 ]], shape=(3, 1), dtype=float32)


In [9]:
#텐서플로 텐서에 값을 할당할 수 ㅇ없음 텐서는 상수

In [10]:
import numpy as np
x=np.ones(shape=(2,2))
x[0,0]=0.

In [11]:
x

array([[0., 1.],
       [1., 1.]])

In [13]:
x= tf.ones(shape=(2,2))
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [15]:
input_var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [22]:
input_var=tf.Variable(3.)
with tf.GradientTape() as tape:
    result= tf.square(input_var)
    gradient=tape.gradient(result, input_var)
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [25]:
input_const=tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result=tf.square(input_const)
gradient = tape.gradient(result, input_const)
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [26]:
##이계도 gradient 가속도 
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2 
    speed = inner_tape.gradient(position,time)
acceleration = outer_tape.gradient (speed,time)

In [27]:
acceleration

<tf.Tensor: shape=(), dtype=float32, numpy=9.8>

In [28]:
def one_training_step(model, images_batch, labels_batch):
    with tf.GradientTape() as tape:
        predictions = model(images_batch)
        per_sample_losses = tf.keras.losses.sparse_categorical_crossentropy(labels_batch, predictions)
        #정방향 패스 gradient block 안에서 
        average_loss = tf.reduce_mean(per_sample_losses)
    gradients=tape.gradient(average_loss,model.weights)
    update_weights(gradients, model.weights) #가중치 업데이트 
    return average_loss

In [30]:
#가중치 업데이트 수동 구현
learning_rate=0.001
def update_weights(gradients, weights):
    for g,w in zip(gradients, weights):
        w.assign_sub(g*learning_rate)

        
#옵티마이저 인스턴스로 자동구현 (실제로는)
from tensorflow.keras import optimizers
optimizer = optimizers.SGD(learning_rate=1e-3)

def update_weights(gradients, weights):
    optimizer.apply_gradients(zip(gradients, weights))

In [ ]:
class NaiveDense:
    def __init__(self, input_size, output_size, activation):
        self.activation = activation
        w_shape = (input_size, output_size)
        w_initial_value = tf.random.uniform (w_shape, minval=0, maxval=1e-1)
        self.W = tf.Variable (w_initial_value)
        
        b_shape=(output_size, )
        b_initial_value= tf.zeros(b_shape)
        self.b = tf.Variable(b_initial_value)
        